### ISSUE TITLE
feature: ability to ignore variables of particular type (results of functions work)

### ISSUE THREAD

**Issue by butuzov** [blizzy78/varnamelen#10]
It would be great if linter can find the type of variable as a result of the function assigment. Like in next example.

```go
func main() {
	e := echo.New()
	e.GET("/", func(c echo.Context) error {
		print("1")
		print("1")
		print("1")
		print("1") 
		print("1")
		return c.String(http.StatusOK, "Hello, World!")
	})
	e.Logger.Fatal(e.Start(":1323"))
}
```

For example this is how we can make it working now. 

```go
func main() {
	var e *echo.Echo
	e = echo.New()
	e.GET("/", func(c echo.Context) error {
		print("1")
		print("1")
		print("1")
		print("1") 
		print("1")
		return c.String(http.StatusOK, "Hello, World!")
	})
	e.Logger.Fatal(e.Start(":1323"))
}
```
I am using it as part of `golangci-lint` with the next configuration.

```yaml
linter-settings:
  varnamelen:
    ignore-decls:
    - c echo.Context 
    - e *echo.Echo
```
