### ISSUE TITLE
Ignore i (index) in for loop

### ISSUE THREAD

**Issue by palsivertsen** [blizzy78/varnamelen#12]
Given this main.go file:
```go
package main

func main() {
	for i := range []struct{}{} {
		/*
			Lorem
			ipsum
			dolor
			sit
			amet.
		*/
		_ = i
	}
}
```
And this config (golangci.yaml):
```yaml
linters:
  disable-all: true
  enable:
    - varnamelen

linters-settings:
  varnamelen:
    ignore-decls:
      - i int
```
I should not get an error for main.go:4:6, but I get the following error when running `golangci-lint run`:
```
main.go:4:6: variable name 'i' is too short for the scope of its usage (varnamelen)
	for i := range []struct{}{} {
	   ^
```
